{{ if .Values.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: replicated-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
{{ end }}
